"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { Container } from "@/components/layout/container";
import { MarketingCtaButton } from "@/components/marketing/marketing-cta-button";

export default function AgenciesPage() {
  const [creatorsCount, setCreatorsCount] = useState(15);
  const [avgRevenuePerCreator, setAvgRevenuePerCreator] = useState(4000);

  // Agency 20% commission estimation
  const grossNetworkRevenue = creatorsCount * avgRevenuePerCreator;
  const estAgencyCommission = Math.round(grossNetworkRevenue * 0.20);

  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      q: "What is the official agency commission split model on Frenzone?",
      a: "Registered agencies earn a 20% agency commission split on the gross streaming revenue generated by all managed creators under their contract.",
    },
    {
      q: "How are agency creator invitations managed?",
      a: "Agencies issue digital invitations via the Agency Portal. Creators accept with 1-click consent, linking them to your agency roster.",
    },
    {
      q: "When are monthly agency payouts disbursed?",
      a: "Agency settlements clear on the 15th of each calendar month via wire transfer into your verified corporate bank account.",
    },
  ];

  return (
    <div>
      {/* Hero */}
      <Container className="py-14 md:py-20">
        <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
          <div>
            <p className="text-sm font-bold uppercase tracking-[0.2em] text-text-muted">Agency program</p>
            <h1 className="mt-4 text-[clamp(44px,6vw,72px)] font-normal tracking-[-0.055em] text-text-primary leading-[0.98]">
              Build a managed creator network.
            </h1>
            <p className="mt-5 max-w-lg text-lg text-text-secondary leading-relaxed">
              Manage creators, compliance, commissions, invoices and coin operations.
            </p>
            <MarketingCtaButton
              type="agency"
              defaultText="Apply now"
              defaultHref="/agency-apply"
              className="mt-8 inline-flex items-center gap-2 rounded-full bg-brand px-6 py-3.5 text-base font-bold text-white shadow-sm hover:bg-brand-hover transition-colors"
            />
          </div>
          <div className="overflow-hidden rounded-[2rem] aspect-square">
            <img
              src="https://frenzone-creator-agency.frenzonelive.chatgpt.site/assets/frenzone-office.jpg"
              alt="Frenzone office"
              className="h-full w-full object-cover"
            />
          </div>
        </div>
      </Container>

      {/* Stats */}
      <section className="bg-surface-muted py-14">
        <Container>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="rounded-3xl bg-surface p-6">
              <p className="text-4xl font-black text-text-primary">20M</p>
              <p className="mt-1 text-text-muted">daily coin limit</p>
            </div>
            <div className="rounded-3xl bg-surface p-6">
              <p className="text-4xl font-black text-text-primary">20%</p>
              <p className="mt-1 text-text-muted">Agency purchase discount</p>
            </div>
            <div className="rounded-3xl bg-surface p-6">
              <p className="text-4xl font-black text-text-primary">11–18%</p>
              <p className="mt-1 text-text-muted">transfer discount</p>
            </div>
            <div className="rounded-3xl bg-surface p-6">
              <p className="text-4xl font-black text-text-primary">$5,000</p>
              <p className="mt-1 text-text-muted">security deposit</p>
            </div>
          </div>
        </Container>
      </section>

      {/* Interactive Agency Commission Calculator */}
      <section id="agency-calculator" className="py-16 border-b border-border">
        <Container>
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-text-primary">Interactive Agency Commission Calculator</h2>
              <p className="text-sm text-text-secondary">
                Estimate monthly agency earnings based on 20% commission split across your creator network.
              </p>
            </div>

            <div className="rounded-3xl border border-border bg-surface p-6 md:p-8">
              <div className="grid gap-8 md:grid-cols-2 items-center">
                <div className="space-y-6">
                  <div>
                    <div className="flex justify-between text-sm font-bold text-text-primary mb-2">
                      <span>Managed Creators Roster</span>
                      <span className="text-brand">{creatorsCount} Creators</span>
                    </div>
                    <input
                      type="range"
                      min={1}
                      max={100}
                      value={creatorsCount}
                      onChange={(e) => setCreatorsCount(Number(e.target.value))}
                      className="w-full accent-brand cursor-pointer"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-sm font-bold text-text-primary mb-2">
                      <span>Avg. Gross Revenue per Creator</span>
                      <span className="text-brand">${avgRevenuePerCreator.toLocaleString()} / mo</span>
                    </div>
                    <input
                      type="range"
                      min={500}
                      max={20000}
                      step={500}
                      value={avgRevenuePerCreator}
                      onChange={(e) => setAvgRevenuePerCreator(Number(e.target.value))}
                      className="w-full accent-brand cursor-pointer"
                    />
                  </div>
                </div>

                <div className="rounded-2xl bg-brand p-6 text-white text-center space-y-3">
                  <span className="text-xs font-bold uppercase tracking-wider text-white/80">Est. Agency Commission (20%)</span>
                  <p className="text-4xl font-black">
                    ${estAgencyCommission.toLocaleString()} <span className="text-sm font-semibold">USD / mo</span>
                  </p>
                  <p className="text-xs text-white/70">Gross Network Revenue: ${grossNetworkRevenue.toLocaleString()} USD</p>
                  <div className="pt-2">
                    <MarketingCtaButton
                      type="agency"
                      defaultText="Become Partner Agency"
                      defaultHref="/agency-apply"
                      className="w-full inline-flex items-center justify-center h-10 px-4 rounded-full font-bold bg-white text-brand hover:bg-white/90 text-sm"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* FAQ */}
      <Container className="py-16">
        <div className="max-w-3xl mx-auto space-y-6">
          <h2 className="text-3xl font-bold text-text-primary text-center">Agency FAQ</h2>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <div key={i} className="rounded-2xl border border-border bg-surface overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex justify-between items-center p-5 text-left font-bold text-text-primary text-sm hover:bg-surface-muted transition-colors"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`h-4 w-4 text-text-muted transition-transform ${openFaq === i ? "rotate-180" : ""}`} />
                </button>
                {openFaq === i && (
                  <div className="px-5 pb-5 pt-1 text-sm text-text-secondary border-t border-border-subtle leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </Container>
    </div>
  );
}
