"use client";

import { useState } from "react";
import Link from "next/link";
import { Building2, ShieldCheck, DollarSign, Users, Award, ArrowRight, ChevronDown, Sparkles } from "lucide-react";
import { Container } from "@/components/layout/container";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";

export default function AgenciesPage() {
  const [creatorsCount, setCreatorsCount] = useState(15);
  const [avgRevenuePerCreator, setAvgRevenuePerCreator] = useState(4000);

  // Agency 20% commission estimation
  const grossNetworkRevenue = creatorsCount * avgRevenuePerCreator;
  const estAgencyCommission = Math.round(grossNetworkRevenue * 0.20);

  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      q: "What is the official agency commission split model on Frenzone?",
      a: "Registered agencies earn a 20% agency commission split on the gross streaming revenue generated by all managed creators under their contract.",
    },
    {
      q: "How are agency creator invitations managed?",
      a: "Agencies issue digital invitations via the Agency Portal. Creators accept with 1-click consent, linking them to your agency roster.",
    },
    {
      q: "When are monthly agency payouts disbursed?",
      a: "Agency settlements clear on the 15th of each calendar month via wire transfer into your verified corporate bank account.",
    },
  ];

  return (
    <div className="space-y-16 py-12">
      {/* Hero Section */}
      <Container>
        <div className="text-center max-w-3xl mx-auto space-y-6">
          <span className="inline-flex items-center space-x-2 rounded-full bg-brand-soft px-4 py-1.5 text-xs font-bold text-brand border border-brand/20">
            <Building2 className="h-3.5 w-3.5" />
            <span>Frenzone Official Agency Program</span>
          </span>

          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl text-text-primary">
            Scale Your Talent Agency with <span className="text-brand">20% Agency Commissions</span>
          </h1>

          <p className="text-lg text-text-secondary leading-relaxed">
            Manage creator rosters, monitor aggregate live streaming hours, and receive monthly corporate wire settlements.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-2">
            <Link href="/agency-apply">
              <Button size="lg" variant="primary" icon={<ArrowRight className="h-5 w-5" />}>
                Apply as Agency Partner
              </Button>
            </Link>
            <Link href="#agency-calculator">
              <Button size="lg" variant="secondary">
                Calculate Agency Commission
              </Button>
            </Link>
          </div>
        </div>
      </Container>

      {/* Interactive Agency Commission Calculator */}
      <section id="agency-calculator" className="bg-surface-muted/60 py-12 border-y border-border">
        <Container>
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-text-primary">Interactive Agency Commission Calculator</h2>
              <p className="text-sm text-text-secondary">
                Estimate monthly agency earnings based on 20% commission split across your creator network.
              </p>
            </div>

            <Card className="p-6 md:p-8 bg-surface shadow-card">
              <div className="grid gap-8 md:grid-cols-2 items-center">
                <div className="space-y-6">
                  <div>
                    <div className="flex justify-between text-sm font-bold text-text-primary mb-2">
                      <span>Managed Creators Roster</span>
                      <span className="text-brand">{creatorsCount} Creators</span>
                    </div>
                    <input
                      type="range"
                      min={1}
                      max={100}
                      value={creatorsCount}
                      onChange={(e) => setCreatorsCount(Number(e.target.value))}
                      className="w-full accent-brand cursor-pointer"
                    />
                  </div>

                  <div>
                    <div className="flex justify-between text-sm font-bold text-text-primary mb-2">
                      <span>Avg. Gross Revenue per Creator</span>
                      <span className="text-brand">${avgRevenuePerCreator.toLocaleString()} / mo</span>
                    </div>
                    <input
                      type="range"
                      min={500}
                      max={20000}
                      step={500}
                      value={avgRevenuePerCreator}
                      onChange={(e) => setAvgRevenuePerCreator(Number(e.target.value))}
                      className="w-full accent-brand cursor-pointer"
                    />
                  </div>
                </div>

                <div className="rounded-2xl bg-gradient-to-br from-brand to-brand-hover p-6 text-white text-center space-y-3 shadow-elevated">
                  <span className="text-xs font-bold uppercase tracking-wider text-brand-soft">Est. Agency Commission (20%)</span>
                  <p className="text-4xl font-black">
                    ${estAgencyCommission.toLocaleString()} <span className="text-sm font-semibold">USD / mo</span>
                  </p>
                  <p className="text-xs text-brand-soft/80">
                    Gross Network Revenue: ${grossNetworkRevenue.toLocaleString()} USD
                  </p>
                  <Link href="/agency-apply" className="block pt-2">
                    <Button variant="secondary" className="w-full bg-white text-brand hover:bg-white/90">
                      Become Partner Agency
                    </Button>
                  </Link>
                </div>
              </div>
            </Card>
          </div>
        </Container>
      </section>

      {/* FAQ Section */}
      <Container>
        <div className="max-w-3xl mx-auto space-y-6">
          <h2 className="text-3xl font-bold text-text-primary text-center">Agency FAQ</h2>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <div key={i} className="rounded-xl border border-border bg-surface overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex justify-between items-center p-4 text-left font-semibold text-text-primary text-sm hover:bg-surface-muted/50 transition-colors"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`h-4 w-4 text-text-muted transition-transform ${openFaq === i ? "rotate-180" : ""}`} />
                </button>
                {openFaq === i && (
                  <div className="px-4 pb-4 pt-1 text-xs text-text-secondary border-t border-border-subtle leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </Container>
    </div>
  );
}
